### ISSUE TITLE
Brainstorm what will and *will not* be taught

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/cog-flow-intro#13]
It is just as important to know what *we will not* cover, as much as what we will cover. For instance, this is a language agnostic course, no Python nor R.

**Comment by lwjohnst86** [comment]
Some ideas...

Will cover:

- Writing in Markdown
- Using Git
- Using GitHub
- Working with at least one other person
- Using (IDE)
- Working with plain text files (as Markdown `.md`)

Will **NOT** cover:

- Using any programming language (e.g. Python or R)
- Getting into project management related to issues/tasks (even though we briefly cover issues)

**Comment by signekb** [comment]
Sounds very good to me! 🌟 
Is the focus on Markdown to help learners to be able to contribute to e.g., the Steno repos/websites?

A bit of a tangent thought: Would that mean that if we include conventional commits, we would almost exclusively use the `docs` prefix? I guess that could get us thinking about how to use the scope element more ...

**Comment by lwjohnst86** [comment]
The focus is on Markdown because it is easy and it doesn't require any prerequisite knowledge aside from knowing what text is. And because it makes it easier to visualization changes made to files in Git and GitHub for reviewing, etc.

**Comment by lwjohnst86** [comment]
Good question about the conventional commits. I'm not sure yet how that will work yet...
