### ISSUE TITLE
Discussion: Agree on what our iteration aim is and if we should create iterations

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/cog-flow-intro#15]
We could do a Kanban approach where we have no iterations and just slowly work away at the task list, while having informal aims that we include in our meeting agendas. Or we could have it a bit more formal and use iterations in the Project board.

**Comment by signekb** [comment]
We go a with Kanban approach for now, and will revise this on planning meetings. 
I will make sure we minimise the number of tasks in "In progress" to keep focus on the most relevant tasks.
