### ISSUE TITLE
Discussion: What skill level should learners have?

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/cog-flow-intro#29]

**Comment by signekb** [comment]
As I said during our meeting this morning, I think I have a tendency to think that we should include more technical stuff like using the Terminal with CLIs (bc I want to expand my own knowledge and usage of those). I think, however, that if we want this course to be doable for e.g., researchers at Steno with less technical experience, we should assume a very basic technical skill level from learners. That would, for instance, not include experience with CLIs or Git - or even an IDE as VSCode.

**Comment by lwjohnst86** [comment]
Yea, agreed. I think making an assumption of: have used Git and/or GitHub a little bit for doing some work or for some courses by using either GitHub UI or using an interface like RStudio or GitHub Desktop, but haven't used it regularly nor used it in a team setting or for collaborating with others.
