### ISSUE TITLE
Brainstorm and create draft of the course learning outcome and objectives

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/cog-flow-intro#4]
Outcome is something bigger ("I will travel to the moon"), while objectives are more concrete and shorter term that fulfil the outcome ("I will make a propulsion system to get into space", "I will make a pod to support life in space", etc).

Put into the `sessions/syllabus.qmd` file.

**Comment by signekb** [comment]
Outcome: 
- Be able to set up and collaborate on projects (with common files) using GitHub

Objectives: 
- Be able to set up a GitHub repository
- Increase the transparency of your work - and your project's history - through atomic commits
- Use the GitHub flow to create branches and review other's pull requests
- Use Issues to track tasks and connect them to pull requests

**Comment by signekb** [comment]
Feedback: 
- Bloom's taxonomy 
- Minimise jargon (like GitHub flow, Issues and atomic commits) also in objectives

**Comment by signekb** [comment]
@lwjohnst86 Here's a revised version of the learning outcome and objectives: 

Course learning outcome:

Be able to: 

- **Collaborate** effectively on shared projects using Git and GitHub.

Objectives:

Be able to:

- **Create** projects on GitHub (*i.e., repos*).
- **Make** small, clear updates to keep your work and the project's progress easy to track (*i.e., commits*).
- **Organise** your tasks separately from others to work efficiently without conflicts (*i.e., branches*).
- **Review** and **provide** feedback on changes made by others (*i.e., PRs*).
- **Track** tasks and link them to project updates (*i.e., issues*).

I'm thinking that the parentheses can be removed if we want to avoid jargon completely. They're just there for clarity/for us right now.

**Comment by lwjohnst86** [comment]
Great starting point!! Here's an expansion on those, refining them to be clearer on the outcome and expectations.

Learning outcome:

1. Describe some core features of effective team-based, collaborative workflows and identify the components that make these workflows effective compared to other workflows. Then use a set of tools and approaches that strongly support effective collaboration.

Learning objectives:

1. Explain what humans as a group need psychologically and organizationally in order to work well together as a team. (*this is to remove thoughts people have that "this doesn't work for me, I work best in chaos", to emphasize, it isn't about individuals, it's about the group*)
2. Discuss the different ways people work together as a team and identify how some ways work better than others for doing effective teamwork.
3. Describe how the widely used Git and GitHub are used for collaboration and explain their biggest strengths (and weaknesses) over alternatives, as well as review the basics of using Git and GitHub.
4. Setup a project on GitHub (called a repository) and apply some key settings to improve collaboration and teamwork.
5. Differentiate between contributor and reviewer/admin roles in a team and why they should be dynamic and explicit.
6. Create and use a task list (called issues) to assign team members to tasks that they are responsible for.
7. Apply a contributor workflow of selecting an issue to work on, creating an isolated section of a repository (called branches), making small and distinct changes to files (called atomic commits) with clear messages on why or what was changed, and contributing those changes into the main branch of a repository in small and distinct steps (called pull requests).
8. Apply a reviewer/admin workflow of reviewing a pull request with changes, giving suggestions and feedback, and identifying how (and if) the changes should be merged back into the main branch of a repository.

We'll probably need to include a definition of collaboration and teamwork and teams somewhere.

**Comment by signekb** [comment]
@lwjohnst86 I very much like the addition of learning objective 1 and 2 that "set the scene" and help learners reflect on collaborative workflows! Yay. 

I think this looks really good 👍 I mainly have questions about what you mean or think to include in specific parts of the learning outcome and objectives:

Learning outcome: 

- I'm wondering what's included in the "compared to other workflows" part of the learning outcome? Are you thinking of less effective workflows of sending the same file around to be reviewed, for instance? Or more in terms of alternatives to Git/GitHub? 

In relation to the learning objectives: 

1. and 2.: Sounds like that could be a full session on its own? Is that also what you're thinking? 
3. Again wondering about what you're thinking about with "alternatives" here? 
4. Which "key settings" are you thinking of here? E.g., protection of the main branch? 
5. About the differentiation of contributor and reviewer/admin, what are your thoughts on why it's important that they're "explicit"? I'm just not sure what you mean here 😄 

Agree that we should define collaboration and teamwork and teams somewhere 👍

**Comment by lwjohnst86** [comment]
For the learning outcome, the "compared to other workflows" is to look at different types and say they *don't* have that makes a workflow effective. The first sentence is tool-agnostic (it isn't about Git and GitHub, and more about, what makes a workflow effective?).

For point 1, probably not a full session, but a few discussion and reading activities throughout the course.

For point 2, the point would be to discuss this and get them thinking, not to necessarily feed them the answer (there isn't really a true answer, only what works better in a given context).

For point 3, you got it :relaxed: 

For point 4, it's so common to have people be contributors, but not really reviewers. This is to highlight, the reviewer role is just as important maybe even more important and people need to recognize and incorporate that into how they work. By recognizing and incorporating it, it by definition becomes explicit. If it isn't explicit, it's implicit, and implicit is generally not great because it assumes everyone knows already (which they don't).

**Comment by signekb** [comment]
Amazing - thanks!
