### ISSUE TITLE
Brainstorm who our intended/assumed learner is

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/cog-flow-intro#7]
Much of what we teach depends *heavily* on who we are actually targeting for the course. Who's the learner who attends or is interested in this?

**Comment by signekb** [comment]
We assume learners:
- Want to work more effectively within a team-based setting on a common set of files
- Have a desire to work together in a more open and transparent way (internally)

Not assuming some affiliation (or past) within research institutions, small-to-medium company, staff, technicians, etc.
